### ISSUE TITLE
Implement the approval and rejection process

### ISSUE THREAD

**Issue by juanbrits** [datopian/ubdc-data-catalogue#18]
### Job Story

When creating a resource, there should be an approval or rejection process so that the UBDC team has an opportunity to assess data before it goes live to the public. 

### Acceptance criteria

- [ ] I can reject/approve a resource submission

**Comment by sagargg** [comment]
Hey @juanbrits,  i see refactoring work is needed for approval extension. It was developed for the FCSC project and some of the code depends on the FCSC custom extension. 
https://github.com/FCSCOpendata/ckanext-datasetapproval

 FYI, It could take 1 to 2 days to finish up. The goal is to make it reusable for other projects. 
 cc @MuhammadIsmailShahzad

**Comment by sagargg** [comment]
@juanbrits  This is deployed on staging env now. You can find the details here  about how it works. 
https://github.com/datopian/ckanext-datasetapproval#approval-flow-for-dataset

Also, note that email notificatioin for approval reques is not functional atm because SMTP info is not configured yet. 


@MuhammadIsmailShahzad  Could you configure STMP in staging env?

**Comment by ismail-shahzad** [comment]
@sagargg Ill enable smtp and get back to you.

**Comment by ismail-shahzad** [comment]
@sagargg SMTP has been enabled

**Comment by sagargg** [comment]
**DONE**
